import { useEffect, useState } from 'react';
import { 
  Newspaper, 
  Terminal, 
  Cpu, 
  Car, 
  Landmark, 
  Users, 
  Music, 
  Fuel,
  ExternalLink,
  Clock
} from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';

// Types
interface NewsItem {
  source: string;
  category: string;
  title: string;
  description: string;
  url: string;
  date: string;
  score: number;
}

// Map categories to icons
const getCategoryIcon = (category: string) => {
  switch (category) {
    case 'IT & AI': return <Cpu className="w-5 h-5 text-blue-500" />;
    case 'Politics': return <Landmark className="w-5 h-5 text-gray-600" />;
    case 'Automotive': return <Car className="w-5 h-5 text-red-500" />;
    case 'HR Analytics': return <Users className="w-5 h-5 text-indigo-500" />;
    case 'Rock & Metal': return <Music className="w-5 h-5 text-purple-500" />;
    case 'Retail & Gas Stations': return <Fuel className="w-5 h-5 text-orange-500" />;
    default: return <Newspaper className="w-5 h-5 text-emerald-500" />;
  }
};

const formatDate = (dateString: string) => {
  const date = new Date(dateString);
  return new Intl.DateTimeFormat('ru-RU', { 
    day: '2-digit', month: 'short', hour: '2-digit', minute: '2-digit' 
  }).format(date);
};

export default function App() {
  const [news, setNews] = useState<NewsItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [activeFilter, setActiveFilter] = useState<string>('All');
  const [showScriptModal, setShowScriptModal] = useState(false);
  const [activeTab, setActiveTab] = useState<'script' | 'env' | 'readme'>('script');

  useEffect(() => {
    // Fetch the JSON generated by our Python script
    fetch('/news_digest.json')
      .then(res => res.json())
      .then(data => {
        setNews(data);
        setLoading(false);
      })
      .catch(err => {
        console.error("Failed to load news", err);
        setLoading(false);
      });
  }, []);

  const categories = ['All', ...Array.from(new Set(news.map(n => n.category)))];
  
  const filteredNews = activeFilter === 'All' 
    ? news 
    : news.filter(n => n.category === activeFilter);

  return (
    <div className="min-h-screen bg-slate-50 text-slate-900 font-sans selection:bg-blue-200">
      {/* Navbar */}
      <nav className="sticky top-0 z-40 w-full backdrop-blur-md bg-white/80 border-b border-slate-200 shadow-sm">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between h-16 items-center">
            <div className="flex items-center gap-2">
              <div className="bg-blue-600 p-2 rounded-lg">
                <Newspaper className="h-6 w-6 text-white" />
              </div>
              <span className="font-bold text-xl tracking-tight text-slate-800">
                Nexus<span className="text-blue-600">Feed</span>
              </span>
            </div>
            
            <div className="flex items-center gap-4">
              <button 
                onClick={() => setShowScriptModal(true)}
                className="flex items-center gap-2 px-4 py-2 bg-slate-900 hover:bg-slate-800 text-white rounded-lg text-sm font-medium transition-colors shadow-sm"
              >
                <Terminal className="w-4 h-4" />
                <span className="hidden sm:inline">View Python Script</span>
              </button>
            </div>
          </div>
        </div>
      </nav>

      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        {/* Header Section */}
        <div className="mb-10 text-center sm:text-left sm:flex sm:items-end sm:justify-between">
          <div>
            <h1 className="text-3xl font-extrabold tracking-tight text-slate-900 sm:text-4xl">
              Daily Top-10 Digest
            </h1>
            <p className="mt-2 text-lg text-slate-600 max-w-2xl">
              Curated news generated by our automated Python aggregator. Focusing on IT, Politics, Auto, HR, Metal, and Retail.
            </p>
          </div>
          <div className="mt-4 sm:mt-0 text-sm font-medium text-slate-500 bg-white px-4 py-2 rounded-full border border-slate-200 shadow-sm inline-flex items-center gap-2">
            <Clock className="w-4 h-4" />
            Last updated: Today, 10:30 AM
          </div>
        </div>

        {/* Filters */}
        <div className="flex flex-wrap gap-2 mb-8">
          {categories.map(cat => (
            <button
              key={cat}
              onClick={() => setActiveFilter(cat)}
              className={`px-4 py-2 rounded-full text-sm font-medium transition-all ${
                activeFilter === cat 
                  ? 'bg-blue-600 text-white shadow-md' 
                  : 'bg-white text-slate-600 hover:bg-slate-100 border border-slate-200'
              }`}
            >
              {cat === 'All' ? 'All Topics' : cat}
            </button>
          ))}
        </div>

        {/* News Grid */}
        {loading ? (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 animate-pulse">
            {[1, 2, 3, 4, 5, 6].map(i => (
              <div key={i} className="bg-white rounded-2xl h-64 border border-slate-100 shadow-sm"></div>
            ))}
          </div>
        ) : (
          <motion.div 
            layout
            className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6"
          >
            <AnimatePresence>
              {filteredNews.map((item, index) => (
                <motion.article
                  layout
                  initial={{ opacity: 0, scale: 0.9 }}
                  animate={{ opacity: 1, scale: 1 }}
                  exit={{ opacity: 0, scale: 0.9 }}
                  transition={{ duration: 0.2 }}
                  key={item.title + index}
                  className="bg-white rounded-2xl border border-slate-200 shadow-sm hover:shadow-xl transition-shadow flex flex-col h-full overflow-hidden group"
                >
                  <div className="p-6 flex flex-col flex-grow">
                    <div className="flex items-center justify-between mb-4">
                      <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-semibold bg-slate-50 text-slate-700 border border-slate-100">
                        {getCategoryIcon(item.category)}
                        {item.category}
                      </span>
                      <span className="text-xs font-medium text-slate-400">
                        {formatDate(item.date)}
                      </span>
                    </div>
                    
                    <h3 className="text-xl font-bold text-slate-900 mb-3 leading-snug group-hover:text-blue-600 transition-colors line-clamp-3">
                      <a href={item.url} target="_blank" rel="noopener noreferrer">
                        {item.title}
                      </a>
                    </h3>
                    
                    <p className="text-slate-600 text-sm flex-grow line-clamp-4 mb-6">
                      {item.description}
                    </p>
                    
                    <div className="pt-4 border-t border-slate-100 flex items-center justify-between mt-auto">
                      <span className="text-xs font-medium text-slate-500 bg-slate-100 px-2 py-1 rounded">
                        {item.source}
                      </span>
                      <a 
                        href={item.url} 
                        target="_blank" 
                        rel="noopener noreferrer"
                        className="inline-flex items-center gap-1 text-sm font-semibold text-blue-600 hover:text-blue-800 transition-colors"
                      >
                        Читать <ExternalLink className="w-3.5 h-3.5" />
                      </a>
                    </div>
                  </div>
                </motion.article>
              ))}
            </AnimatePresence>
          </motion.div>
        )}
      </main>

      {/* Script Modal */}
      <AnimatePresence>
        {showScriptModal && (
          <div className="fixed inset-0 z-50 flex items-center justify-center p-4 sm:p-6">
            <motion.div 
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="absolute inset-0 bg-slate-900/60 backdrop-blur-sm"
              onClick={() => setShowScriptModal(false)}
            />
            <motion.div 
              initial={{ opacity: 0, y: 20, scale: 0.95 }}
              animate={{ opacity: 1, y: 0, scale: 1 }}
              exit={{ opacity: 0, y: 20, scale: 0.95 }}
              className="relative bg-slate-900 rounded-2xl w-full max-w-5xl max-h-[90vh] flex flex-col shadow-2xl overflow-hidden border border-slate-700"
            >
              <div className="flex flex-col sm:flex-row sm:items-center justify-between px-6 py-3 border-b border-slate-800 bg-slate-900/80">
                <div className="flex items-center gap-6 overflow-x-auto">
                  <div className="flex gap-1.5 hidden sm:flex">
                    <div className="w-3 h-3 rounded-full bg-red-500"></div>
                    <div className="w-3 h-3 rounded-full bg-yellow-500"></div>
                    <div className="w-3 h-3 rounded-full bg-green-500"></div>
                  </div>
                  <div className="flex space-x-1">
                    <button onClick={() => setActiveTab('script')} className={`px-4 py-2 rounded-t-lg font-mono text-sm transition-colors ${activeTab === 'script' ? 'bg-[#0d1117] text-white border-t border-x border-slate-700' : 'text-slate-400 hover:text-slate-200'}`}>news_aggregator.py</button>
                    <button onClick={() => setActiveTab('env')} className={`px-4 py-2 rounded-t-lg font-mono text-sm transition-colors ${activeTab === 'env' ? 'bg-[#0d1117] text-white border-t border-x border-slate-700' : 'text-slate-400 hover:text-slate-200'}`}>.env.example</button>
                    <button onClick={() => setActiveTab('readme')} className={`px-4 py-2 rounded-t-lg font-mono text-sm transition-colors ${activeTab === 'readme' ? 'bg-[#0d1117] text-white border-t border-x border-slate-700' : 'text-slate-400 hover:text-slate-200'}`}>README.md</button>
                  </div>
                </div>
                <button 
                  onClick={() => setShowScriptModal(false)}
                  className="text-slate-400 hover:text-white transition-colors text-sm font-medium px-3 py-1 bg-slate-800 rounded-md"
                >
                  Close
                </button>
              </div>
              
              <div className="p-6 overflow-y-auto custom-scrollbar bg-[#0d1117] text-slate-300 font-mono text-sm leading-relaxed min-h-[50vh]">
                <pre><code>
                  {activeTab === 'script' && PYTHON_SCRIPT_CODE}
                  {activeTab === 'env' && ENV_CODE}
                  {activeTab === 'readme' && README_CODE}
                </code></pre>
              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>

      <style>{`
        .custom-scrollbar::-webkit-scrollbar {
          width: 8px;
        }
        .custom-scrollbar::-webkit-scrollbar-track {
          background: #0d1117; 
        }
        .custom-scrollbar::-webkit-scrollbar-thumb {
          background: #30363d; 
          border-radius: 4px;
        }
        .custom-scrollbar::-webkit-scrollbar-thumb:hover {
          background: #484f58; 
        }
      `}</style>
    </div>
  );
}

const PYTHON_SCRIPT_CODE = `import os
import json
import logging
import asyncio
from typing import List, Dict, Any

import requests
from dotenv import load_dotenv
from telethon import TelegramClient
from telethon.errors import SessionPasswordNeededError

# Настройка логирования
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

load_dotenv()

# Ключи API
NEWSAPI_KEY = os.getenv('NEWSAPI_KEY')
TG_API_ID = int(os.getenv('TG_API_ID', 0))
TG_API_HASH = os.getenv('TG_API_HASH')
TG_PHONE = os.getenv('TG_PHONE')

NEWSAPI_TOPICS = {
    "IT & AI": "artificial intelligence OR software development OR IT industry",
    "Politics": "politics OR government",
    "Automotive": "automotive OR cars OR electric vehicles",
    "HR Analytics": "HR analytics OR human resources trends",
    "Rock & Metal": "rock music OR metal music",
    "Retail & Gas Stations": "retail OR gas station OR fuel market"
}

TELEGRAM_CHANNELS = [
    'it_news_channel',      # IT & AI
    'politics_channel_ru',  # Политика
    'auto_news_ru',         # Авто
    'hr_trends_ru',         # HR
    'rock_metal_news',      # Рок/Метал
    'retail_neft'           # Ритейл и АЗС (Нефтьмагистраль)
]

class NewsAggregator:
    def __init__(self):
        self.news_items = []
        
    def fetch_news_api(self):
        logger.info("Запуск сбора новостей через NewsAPI...")
        base_url = "https://newsapi.org/v2/everything"
        for category, query in NEWSAPI_TOPICS.items():
            try:
                params = {
                    'q': query, 'language': 'ru', 'sortBy': 'publishedAt',
                    'pageSize': 3, 'apiKey': NEWSAPI_KEY
                }
                response = requests.get(base_url, params=params)
                response.raise_for_status()
                for article in response.json().get('articles', []):
                    if article['title']:
                        self.news_items.append({
                            'source': f"NewsAPI ({article['source']['name']})",
                            'category': category,
                            'title': article['title'],
                            'description': article['description'] or '',
                            'url': article['url'],
                            'date': article['publishedAt'],
                            'score': 10
                        })
            except Exception as e:
                logger.error(f"Ошибка NewsAPI ({category}): {e}")

    async def fetch_telegram_news(self):
        if not TG_API_ID or not TG_API_HASH:
            logger.warning("Telegram API креды не заданы. Пропуск.")
            return

        logger.info("Сбор новостей из Telegram...")
        client = TelegramClient('news_session', TG_API_ID, TG_API_HASH)
        await client.connect()
        
        # Авторизация если нужно (отправка кода на TG_PHONE)
        if not await client.is_user_authorized():
            await client.send_code_request(TG_PHONE)
            await client.sign_in(TG_PHONE, input('Код из Telegram: '))
                
        for channel in TELEGRAM_CHANNELS:
            try:
                async for message in client.iter_messages(channel, limit=3):
                    if message.text:
                        lines = message.text.strip().split('\\n')
                        self.news_items.append({
                            'source': f"Telegram (@{channel})",
                            'category': 'Telegram Feed',
                            'title': lines[0][:100] + '...',
                            'description': message.text[:200] + '...',
                            'url': f"https://t.me/{channel}/{message.id}",
                            'date': message.date.isoformat(),
                            'score': 15
                        })
            except Exception as e:
                logger.error(f"Ошибка канала {channel}: {e}")
        await client.disconnect()

    def rank_and_export(self, filename="public/news_digest.json"):
        # Сортировка по дате и удаление дубликатов
        sorted_news = sorted(self.news_items, key=lambda x: x['date'], reverse=True)
        unique_news = {item['title']: item for item in sorted_news}.values()
        top_10 = list(unique_news)[:10]
        
        with open(filename, 'w', encoding='utf-8') as f:
            json.dump(top_10, f, ensure_ascii=False, indent=4)
        logger.info(f"Топ-10 сохранен в {filename}")

async def main():
    aggregator = NewsAggregator()
    aggregator.fetch_news_api()
    await aggregator.fetch_telegram_news()
    aggregator.rank_and_export()

if __name__ == "__main__":
    asyncio.run(main())
`;

const ENV_CODE = `# NewsAPI
NEWSAPI_KEY=your_news_api_key_here

# Telegram (Telethon) - Получить на https://my.telegram.org/apps
TG_API_ID=your_api_id_here
TG_API_HASH=your_api_hash_here
TG_PHONE=+1234567890

# Темы для парсинга
# IT & AI, Politics, Auto, HR Analytics, Rock/Metal, Retail & Gas
`;

const README_CODE = `# Python News Aggregator

Масштабируемый скрипт для сбора новейших и самых интересных новостей по вашим интересам.
Интегрирует NewsAPI для сбора статей и Telethon для чтения Telegram-каналов напрямую.

## Требования

- Python 3.8+

## Установка

1. Создайте виртуальное окружение:
python -m venv venv
source venv/bin/activate  # Для Linux/Mac
venv\\Scripts\\activate     # Для Windows

2. Установите зависимости:
pip install requests python-dotenv telethon

3. Настройте файл переменных окружения:
- Скопируйте .env.example в .env
- Получите API-ключ для NewsAPI
- Получите api_id и api_hash для Telegram на my.telegram.org/apps
- Впишите ваши данные в .env

## Запуск скрипта

Запустите скрипт командой:
python news_aggregator.py

При первом запуске Telethon может запросить код подтверждения, который придёт в ваш аккаунт Telegram.

## Как это работает?

- Скрипт синхронно собирает новости из NewsAPI по ключевым словам.
- Асинхронно подключается к Telegram через Telethon и забирает последние посты из каналов.
- Оценивает и фильтрует уникальные новости, собирая Топ-10 дайджест.
- Сохраняет результат в формате JSON, откуда фронтенд читает его.
`;
